"""new record are add 

Revision ID: 0551967971ab
Revises: 63e4494e4c91
Create Date: 2026-06-23 09:10:46.301414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0551967971ab'
down_revision: Union[str, Sequence[str], None] = '63e4494e4c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('subcription', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'organisation', 'subscriptions', ['subcription'], ['id'])
    op.add_column('subscriptions', sa.Column('starting_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'starting_date')
    op.drop_constraint(None, 'organisation', type_='foreignkey')
    op.drop_column('organisation', 'subcription')
    # ### end Alembic commands ###
