"""role table relation name with user corection

Revision ID: 078dffbdc9a8
Revises: 5099c630f8a0
Create Date: 2026-07-16 11:46:36.307731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '078dffbdc9a8'
down_revision: Union[str, Sequence[str], None] = '5099c630f8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.alter_column('permissions', 'scope',
               existing_type=postgresql.ENUM('ORGANIZATION', 'SYSTEM_ADMIN', name='permissionscopenum'),
               type_=postgresql.ENUM('ORGANIZATION', 'SYSTEM', name='permissionscopenumupdate'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'scope',
               existing_type=postgresql.ENUM('ORGANIZATION', 'SYSTEM_ADMIN', name='permissionscopenumupdate'),
               type_=postgresql.ENUM('ORGANIZATION', 'SYSTEM_ADMIN', name='permissionscopenum'),
               existing_nullable=False)
    op.create_table('token',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['userdevice.id'], name=op.f('token_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('token_pkey'))
    )
    # ### end Alembic commands ###
