"""team model added and some model changes in holydays

Revision ID: 0c7760d87f2f
Revises: e6bf6ac898ab
Create Date: 2026-09-25 10:51:20.403592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7760d87f2f'
down_revision: Union[str, Sequence[str], None] = 'e6bf6ac898ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='organizationstatus'), nullable=False))
    op.add_column('department', sa.Column('department_head', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'department', 'employees', ['department_head'], ['id'])
    op.add_column('employee_details', sa.Column('employee_profile_image', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'employee_role', ['id'])
    op.add_column('shift', sa.Column('break_type', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user_role', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='unique')
    op.drop_column('shift', 'break_type')
    op.drop_constraint(None, 'employee_role', type_='unique')
    op.drop_column('employee_details', 'employee_profile_image')
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'department_head')
    op.drop_column('branches', 'status')
    # ### end Alembic commands ###
