"""dev-ashu : attendance evidance model added

Revision ID: 11b190267363
Revises: e2bae631c0a9
Create Date: 2026-09-11 11:32:51.769051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b190267363'
down_revision: Union[str, Sequence[str], None] = 'e2bae631c0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_record_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attendance_record_id', sa.UUID(), nullable=False),
    sa.Column('face_match_score', sa.Float(), nullable=True),
    sa.Column('type', sa.Enum('CHECKIN', 'CHECKOUT', name='typeattendance'), nullable=True),
    sa.Column('face_profile_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ),
    sa.PrimaryKeyConstraint('id', 'attendance_record_id')
    )
    op.add_column('branches', sa.Column('total_number_of_paid_leaves', sa.Integer(), nullable=False))
    op.add_column('shift', sa.Column('break_time_minutes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift', 'break_time_minutes')
    op.drop_column('branches', 'total_number_of_paid_leaves')
    op.drop_table('attendance_record_evidence')
    # ### end Alembic commands ###
