"""index add to entity

Revision ID: 121b51f2f0b1
Revises: 584771745183
Create Date: 2026-07-11 09:57:23.203329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '121b51f2f0b1'
down_revision: Union[str, Sequence[str], None] = '584771745183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.create_index(op.f('ix_attendance_log_oranisation_id'), 'attendance_log', ['oranisation_id'], unique=False)
    op.create_index('idx_attendance_date', 'attendance_records', ['employee_id', 'organisation_id', 'attendance_date'], unique=False)
    op.create_index('idx_attendance_status', 'attendance_records', ['organisation_id', 'status'], unique=False)
    op.create_index('organisation_id', 'department', ['name'], unique=False)
    op.add_column('employee_details', sa.Column('dob', sa.Date(), nullable=True))
    op.create_index('employee_id', 'employee_details', ['full_name', 'dob', 'gender', 'marital_status'], unique=False)
    op.create_index('idx_cityemployee_id', 'employee_details', ['full_name', 'city'], unique=False)
    op.create_index('employee_id_idx', 'employee_documents', ['employee_id'], unique=True)
    op.alter_column(

        "employees",

        "emplopyee_status",  # old name

        new_column_name="employee_status",

    )
    op.create_index('idx_employee_code', 'employees', ['employee_code', 'organisation_id'], unique=False)
    op.create_index('idx_employee_id', 'employees', ['id', 'employee_code', 'organisation_id'], unique=False)
    op.create_index('idx_employee_status', 'employees', ['employee_status'], unique=False)
    op.add_column('leave_requests', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'leave_requests', 'organisation', ['organization_id'], ['id'])
    op.create_index('idx_user_email', 'user', ['email', 'id'], unique=False)
    op.create_index('idx_user_organisation_id', 'user', ['organisation_id', 'id'], unique=False)
    op.create_index('idx_user_device', 'userdevice', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_device', table_name='userdevice')
    op.drop_index('idx_user_organisation_id', table_name='user')
    op.drop_index('idx_user_email', table_name='user')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_column('leave_requests', 'organization_id')
    op.alter_column(

            "employees",

            "employee_status",  # current name

            new_column_name="emplopyee_status",

        )
    op.drop_index('idx_employee_id', table_name='employees')
    op.drop_index('idx_employee_code', table_name='employees')
    op.drop_column('employees', 'employee_status')
    op.drop_index('employee_id_idx', table_name='employee_documents')
    op.drop_index('idx_cityemployee_id', table_name='employee_details')
    op.drop_index('employee_id', table_name='employee_details')
    op.drop_column('employee_details', 'dob')
    op.drop_index('organisation_id', table_name='department')
    op.drop_index('idx_attendance_status', table_name='attendance_records')
    op.drop_index('idx_attendance_date', table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_log_oranisation_id'), table_name='attendance_log')
    op.create_table('token',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['userdevice.id'], name=op.f('token_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('token_pkey'))
    )
    # ### end Alembic commands ###
