"""new record add face embening for employee

Revision ID: 1f914d2ddff8
Revises: 121b51f2f0b1
Create Date: 2026-07-13 11:38:22.307957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f914d2ddff8'
down_revision: Union[str, Sequence[str], None] = '121b51f2f0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.alter_column('employee_details', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('employees', sa.Column('employee_face_embedding', sa.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'employee_face_embedding')
    op.alter_column('employee_details', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_table('token',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['userdevice.id'], name=op.f('token_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('token_pkey'))
    )
    # ### end Alembic commands ###
