"""Initial migration

Revision ID: 2086d0cd2436
Revises: 
Create Date: 2026-07-15 08:38:27.287488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2086d0cd2436'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('organisation_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='organizationstatus'), nullable=False),
    sa.Column('organisation_email', sa.String(length=225), nullable=False),
    sa.Column('address', sa.String(length=225), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('allowed_radius', sa.Integer(), nullable=True),
    sa.Column('number_of_employee', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisation_organisation_code'), 'organisation', ['organisation_code'], unique=True)
    op.create_index(op.f('ix_organisation_organisation_email'), 'organisation', ['organisation_email'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('scope', postgresql.ENUM('ORGANIZATION', 'SYSTEM_ADMIN', name='permissionscopenum'), nullable=False),
    sa.Column('assignable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('department_status', postgresql.ENUM('ACTIVATE', 'DEACTIVATE', 'DELETED', name='departmentstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'name', name='uq_department_org_name')
    )
    op.create_index('organisation_id', 'department', ['name'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=22), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('subscription_type', sa.Enum('YEARLY', 'MONTHLY', name='subscriptiontype'), nullable=False),
    sa.Column('starting_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=225), nullable=False),
    sa.Column('email', sa.String(length=225), nullable=False),
    sa.Column('profile_image', sa.String(length=225), nullable=True),
    sa.Column('password_hash', sa.String(length=225), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'ORG_ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='userstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_user_email', 'user', ['email', 'id'], unique=False)
    op.create_index('idx_user_organisation_id', 'user', ['organisation_id', 'id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('employee_status', postgresql.ENUM('ACTIVE', 'SUSPENDED', 'DELETE', name='employeestatus'), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('work_mode', postgresql.ENUM('WFH', 'WFO', name='workmode'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code'),
    sa.UniqueConstraint('organisation_id', 'employee_code', name='uq_org_employee_code')
    )
    op.create_index('idx_employee_code', 'employees', ['employee_code', 'organisation_id'], unique=False)
    op.create_index('idx_employee_id', 'employees', ['id', 'employee_code', 'organisation_id'], unique=False)
    op.create_index('idx_employee_status', 'employees', ['employee_status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('temp_otp_storage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('otp', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('expire_time', sa.Time(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userdevice',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('device_unique_id', sa.String(), nullable=False),
    sa.Column('firebase_fcm_token', sa.String(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('is_login', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_unique_id')
    )
    op.create_index('idx_user_device', 'userdevice', ['user_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('is_punchin', sa.Boolean(), nullable=False),
    sa.Column('punchin_time', sa.Time(), nullable=False),
    sa.Column('is_punchout', sa.Boolean(), nullable=False),
    sa.Column('punchout_time', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LEAVE', name='attendancestatus', native_enum=False), nullable=False),
    sa.Column('work_mode', sa.Enum('WFH', 'WFO', name='workmode', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'attendance_date', name='uq_employee_attendance_date')
    )
    op.create_index('idx_attendance_date', 'attendance_records', ['employee_id', 'organisation_id', 'attendance_date'], unique=False)
    op.create_index('idx_attendance_status', 'attendance_records', ['organisation_id', 'status'], unique=False)
    op.create_table('employee_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('marital_status', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('employee_id', 'employee_details', ['full_name', 'dob', 'gender', 'marital_status'], unique=False)
    op.create_index('idx_cityemployee_id', 'employee_details', ['full_name', 'city'], unique=False)
    op.create_table('employee_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('aadhaar_document_url', sa.String(length=500), nullable=True),
    sa.Column('pan_document_url', sa.String(length=500), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index('employee_id_idx', 'employee_documents', ['employee_id'], unique=True)
    op.create_table('leave_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leavestatus'), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attendance_records_id', sa.UUID(), nullable=False),
    sa.Column('oranisation_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('log', sa.String(length=225), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_records_id'], ['attendance_records.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['userdevice.id'], ),
    sa.ForeignKeyConstraint(['oranisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_log_oranisation_id'), 'attendance_log', ['oranisation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_log_oranisation_id'), table_name='attendance_log')
    op.drop_table('attendance_log')
    op.drop_table('leave_requests')
    op.drop_index('employee_id_idx', table_name='employee_documents')
    op.drop_table('employee_documents')
    op.drop_index('idx_cityemployee_id', table_name='employee_details')
    op.drop_index('employee_id', table_name='employee_details')
    op.drop_table('employee_details')
    op.drop_index('idx_attendance_status', table_name='attendance_records')
    op.drop_index('idx_attendance_date', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('idx_user_device', table_name='userdevice')
    op.drop_table('userdevice')
    op.drop_table('temp_otp_storage')
    op.drop_table('role_permissions')
    op.drop_index('idx_employee_status', table_name='employees')
    op.drop_index('idx_employee_id', table_name='employees')
    op.drop_index('idx_employee_code', table_name='employees')
    op.drop_table('employees')
    op.drop_index('idx_user_organisation_id', table_name='user')
    op.drop_index('idx_user_email', table_name='user')
    op.drop_table('user')
    op.drop_table('subscriptions')
    op.drop_table('shift')
    op.drop_table('role')
    op.drop_index('organisation_id', table_name='department')
    op.drop_table('department')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organisation_organisation_email'), table_name='organisation')
    op.drop_index(op.f('ix_organisation_organisation_code'), table_name='organisation')
    op.drop_table('organisation')
    # ### end Alembic commands ###
