"""correction

Revision ID: 2f1bb837573a
Revises: 92c5da345de9
Create Date: 2026-07-20 12:04:18.355706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f1bb837573a'
down_revision: Union[str, Sequence[str], None] = '92c5da345de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.drop_constraint(op.f('employee_role_role_id_fkey'), 'employee_role', type_='foreignkey')
    op.drop_column('employee_role', 'role_id')
    op.alter_column('user', 'organisation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user', 'account_type',
               existing_type=postgresql.ENUM('SYSTEM', 'ORGANISATION', name='accounttype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'account_type',
               existing_type=postgresql.ENUM('SYSTEM', 'ORGANISATION', name='accounttype'),
               nullable=True)
    op.alter_column('user', 'organisation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('employee_role', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('employee_role_role_id_fkey'), 'employee_role', 'organisation_roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_table('token',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['userdevice.id'], name=op.f('token_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('token_pkey'))
    )
    # ### end Alembic commands ###
