"""otp table now otp feild created

Revision ID: 3561fb56d126
Revises: e5453c43bfc1
Create Date: 2026-07-05 11:32:01.862944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3561fb56d126'
down_revision: Union[str, Sequence[str], None] = 'e5453c43bfc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_otp_storage', sa.Column('otp', sa.String(), nullable=False))
    op.add_column('temp_otp_storage', sa.Column('is_expired', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_otp_storage', 'is_expired')
    op.drop_column('temp_otp_storage', 'otp')
    # ### end Alembic commands ###
