"""organisation has connect to subscription 

Revision ID: 3939fe218014
Revises: d0f8c672cd32
Create Date: 2026-06-23 11:27:25.175676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3939fe218014'
down_revision: Union[str, Sequence[str], None] = 'd0f8c672cd32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organisation', 'organisation_code',
               existing_type=sa.VARCHAR(length=225),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_unique_constraint(None, 'subscriptions', ['organisation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.alter_column('organisation', 'organisation_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=225),
               existing_nullable=False)
    # ### end Alembic commands ###
