"""User table has a status colouduakda1

Revision ID: 3e0926df4e79
Revises: b289ae74bb9f
Create Date: 2026-06-29 12:32:49.568580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0926df4e79'
down_revision: Union[str, Sequence[str], None] = 'b289ae74bb9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'shift_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'shift_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
