"""employee model details change

Revision ID: 4297ec549e84
Revises: f81547533b6f
Create Date: 2026-09-27 16:57:11.757046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4297ec549e84'
down_revision: Union[str, Sequence[str], None] = 'f81547533b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_details', sa.Column('street', sa.String(length=30), nullable=True))
    op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('team_id', sa.UUID(), nullable=True))
    op.add_column('employees', sa.Column('organisation_branch_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('employees_organisation_branch_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'branches', ['organisation_branch_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'department', ['department_id'], ['id'])
    op.drop_column('employees', 'organisation_branch')
    op.drop_column('employees', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('organisation_branch', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_organisation_branch_fkey'), 'employees', 'branches', ['organisation_branch'], ['id'])
    op.drop_column('employees', 'organisation_branch_id')
    op.drop_column('employees', 'team_id')
    op.drop_column('employees', 'department_id')
    op.drop_column('employee_details', 'street')
    # ### end Alembic commands ###
