"""new role permission setup

Revision ID: 4537285c9ace
Revises: 0010d8ef45da
Create Date: 2026-07-17 12:37:00.837460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4537285c9ace'
down_revision: Union[str, Sequence[str], None] = '0010d8ef45da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.add_column('user', sa.Column('account_type', sa.Enum('SYSTEM', 'ORGANISATION', name='accounttype'), nullable=True))
    op.drop_constraint(op.f('user_role_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'system_role')
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('system_role', postgresql.ENUM('SYSTEM_USER', 'SYSTEM_ACCOUNTANT', 'SYSTEM_MANAGER', 'SYSTEM_ADMIN', name='userroleupdated'), server_default=sa.text("'SYSTEM_USER'::userroleupdated"), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('user_role_id_fkey'), 'user', 'role', ['role_id'], ['id'])
    op.drop_column('user', 'account_type')
    op.create_table('token',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['userdevice.id'], name=op.f('token_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('token_pkey'))
    )
    # ### end Alembic commands ###
