"""new feild are add , created , updated , approved by , employee table connect to user table  

Revision ID: 4f8df5b58317
Revises: dd86f48cb570
Create Date: 2026-06-23 07:48:13.247393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f8df5b58317'
down_revision: Union[str, Sequence[str], None] = 'dd86f48cb570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

employee_status_enum = postgresql.ENUM(
    'ACTIVE',
    'SUSPENDED',
    'DELETE',
    name='employeestatus'
)
employee_status_enum.create(op.get_bind(), checkfirst=True)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column(
    'employees',
    sa.Column(
        'emplopyee_status',
        employee_status_enum,
        nullable=False
    )
)
    op.add_column('employees', sa.Column('join_date', sa.Date(), nullable=False))
    op.add_column('employees', sa.Column('manaer_id', sa.UUID(), nullable=False))
    op.add_column('employees', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('employees', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'employees', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'user', ['manaer_id'], ['id'])
    op.add_column('leave_requests', sa.Column('approved_by', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'leave_requests', 'user', ['approved_by'], ['id'])
    op.add_column('user', sa.Column('profile_image', sa.String(length=225), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_column('leave_requests', 'approved_by')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'updated_at')
    op.drop_column('employees', 'created_at')
    op.drop_column('employees', 'manaer_id')
    op.drop_column('employees', 'join_date')
    op.drop_column('employees', 'emplopyee_status')
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###
