"""User table change  

Revision ID: 505755f76cf5
Revises: 20f0bb8120d2
Create Date: 2026-06-29 09:14:06.791750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '505755f76cf5'
down_revision: Union[str, Sequence[str], None] = '20f0bb8120d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_image',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    op.alter_column('user', 'profile_image',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    # ### end Alembic commands ###
