"""new update insisde table

Revision ID: 5099c630f8a0
Revises: 2086d0cd2436
Create Date: 2026-07-16 10:47:26.363659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5099c630f8a0'
down_revision: Union[str, Sequence[str], None] = '2086d0cd2436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.add_column('subscriptions', sa.Column('ending_date', sa.DateTime(), nullable=False))
    op.add_column('subscriptions', sa.Column('subscription_duration', sa.Enum('UNDEFIND', 'YEARLY', 'MONTHLY', name='subscriptionduratioorg'), nullable=True))
    op.add_column('subscriptions', sa.Column('subscription_status', sa.Enum('ACTIVE', 'EXPIRED', 'SUSPENDED', name='subscriptionstatusorg'), nullable=False))
    op.alter_column('subscriptions', 'subscription_type',
               existing_type=postgresql.ENUM('YEARLY', 'MONTHLY', name='subscriptiontype'),
               type_=sa.Enum('FREEIMUM', 'BASIC', 'PREMIMUM', name='subscriptiontypeorg'),
               existing_nullable=False)
    op.add_column(
    "user",
    sa.Column(
        "system_role",
        sa.Enum(
            "SYSTEM_USER",
            "SYSTEM_ACCOUNTANT",
            "SYSTEM_MANAGER",
            "SYSTEM_ADMIN",
            name="userroleupdated",
        ),
        nullable=False,
        server_default="SYSTEM_USER",
    ),
    ),
    op.add_column('user', sa.Column('role_id', sa.UUID(), nullable=True)),
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', postgresql.ENUM('ADMIN', 'USER', 'ORG_ADMIN', 'SUPER_ADMIN', name='userrole'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'system_role')
    op.alter_column('subscriptions', 'subscription_type',
               existing_type=sa.Enum('FREEIMUM', 'BASIC', 'PREMIMUM', name='subscriptiontypeorg'),
               type_=postgresql.ENUM('YEARLY', 'MONTHLY', name='subscriptiontype'),
               existing_nullable=False)
    op.drop_column('subscriptions', 'subscription_status')
    op.drop_column('subscriptions', 'subscription_duration')
    op.drop_column('subscriptions', 'ending_date')
    op.create_table('token',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['userdevice.id'], name=op.f('token_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('token_pkey'))
    )
    # ### end Alembic commands ###
