"""User table has a status coloumn1

Revision ID: 50fd205791a4
Revises: 74adadfc5b8f
Create Date: 2026-06-29 10:51:07.573631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50fd205791a4'
down_revision: Union[str, Sequence[str], None] = '74adadfc5b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'SUSPENDED', 'DELETED', name='userstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'SUSPENDED', 'DELETED', name='userstatus'),
               nullable=True)
    # ### end Alembic commands ###
