"""dev-ashu : attendane_evidence model attendance_record_id update

Revision ID: 56cec3a1bf90
Revises: 11b190267363
Create Date: 2026-09-11 13:26:36.402335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56cec3a1bf90'
down_revision: Union[str, Sequence[str], None] = '11b190267363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
