"""employee table droped

Revision ID: 63e4494e4c91
Revises: 4f8df5b58317
Create Date: 2026-06-23 08:03:15.385232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e4494e4c91'
down_revision: Union[str, Sequence[str], None] = '4f8df5b58317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employees_manaer_id_fkey'), 'employees', type_='foreignkey')
    op.drop_column('employees', 'manaer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('manaer_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('employees_manaer_id_fkey'), 'employees', 'user', ['manaer_id'], ['id'])
    # ### end Alembic commands ###
