"""attendacne also save the workdone

Revision ID: 663261609f46
Revises: c26808c0c56e
Create Date: 2026-06-27 09:03:24.211784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '663261609f46'
down_revision: Union[str, Sequence[str], None] = 'c26808c0c56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('work_mode', sa.Enum('WFH', 'WFO', name='workmode', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_records', 'work_mode')
    # ### end Alembic commands ###
