"""New table add as employee face  mess

Revision ID: 6df2ac84bd22
Revises: 08d2c6cf2be9
Create Date: 2026-08-05 11:19:10.213649

"""
from typing import Sequence, Union

from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df2ac84bd22'
down_revision: Union[str, Sequence[str], None] = '08d2c6cf2be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ##
    op.create_table(
            "employee_face",
            sa.Column(
                "id",
                sa.UUID(),
                nullable=False,
            ),
            sa.Column(
                "employee_id",
                sa.UUID(),
                nullable=False,
            ),
            sa.Column(
                "embedding",
                postgresql.JSONB(astext_type=sa.Text()),
                nullable=False,
            ),
            sa.Column(
                "created_at",
                sa.DateTime(),
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(
                ["employee_id"],
                ["employees.id"],
                ondelete="CASCADE",
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    op.create_index(
            "idx_employee_face_id",
            "employee_face",
            ["employee_id"],
            unique=True,
        )
    op.create_table('token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['userdevice.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.drop_index('idx_employee_face_id', table_name='employee_face')
    op.drop_table('employee_face')
    # ### end Alembic commands ###
