"""table oranisation table user staud 

Revision ID: 74adadfc5b8f
Revises: 505755f76cf5
Create Date: 2026-06-29 10:16:16.816369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74adadfc5b8f'
down_revision: Union[str, Sequence[str], None] = '505755f76cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='userstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
