"""work mode change to employee78352

Revision ID: 7e4997e8c697
Revises: 5b5d0e64a6f5
Create Date: 2026-06-28 21:33:07.512167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4997e8c697'
down_revision: Union[str, Sequence[str], None] = '5b5d0e64a6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employe_shift', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'employees', 'shift', ['employe_shift'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'employe_shift')
    # ### end Alembic commands ###
