"""employee has supervisor and employee assign to beanches

Revision ID: 83dc18975b08
Revises: dd900dbf585e
Create Date: 2026-09-26 08:53:46.955779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83dc18975b08'
down_revision: Union[str, Sequence[str], None] = 'dd900dbf585e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('organisation_branch', sa.UUID(), nullable=True))
    op.add_column('employees', sa.Column('supervisor', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'employees', 'employees', ['supervisor'], ['id'])
    op.create_foreign_key(None, 'employees', 'branches', ['organisation_branch'], ['id'])
    op.alter_column('teams', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teams', 'delete_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'delete_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('teams', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'supervisor')
    op.drop_column('employees', 'organisation_branch')
    # ### end Alembic commands ###
