"""shift correction

Revision ID: 85e2d151da91
Revises: 7e4997e8c697
Create Date: 2026-06-28 21:37:54.402108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e2d151da91'
down_revision: Union[str, Sequence[str], None] = '7e4997e8c697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('shift_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('employees_employe_shift_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'shift', ['shift_id'], ['id'])
    op.drop_column('employees', 'employe_shift')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employe_shift', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_employe_shift_fkey'), 'employees', 'shift', ['employe_shift'], ['id'])
    op.drop_column('employees', 'shift_id')
    # ### end Alembic commands ###
