"""beanch map with sift attendacne and other table 

Revision ID: 8ad0782beb32
Revises: 83dc18975b08
Create Date: 2026-09-26 09:41:23.573091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad0782beb32'
down_revision: Union[str, Sequence[str], None] = '83dc18975b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('branches', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'attendance_records', 'branches', ['branches'], ['id'])
    op.add_column('organisation_calendar', sa.Column('organisation_branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'organisation_calendar', 'branches', ['organisation_branch_id'], ['id'], ondelete='CASCADE')
    op.add_column('organisation_roles', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'organisation_roles', 'branches', ['branch_id'], ['id'])
    op.add_column('shift', sa.Column('branch_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'shift', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shift', type_='foreignkey')
    op.drop_column('shift', 'branch_id')
    op.drop_constraint(None, 'organisation_roles', type_='foreignkey')
    op.drop_column('organisation_roles', 'branch_id')
    op.drop_constraint(None, 'organisation_calendar', type_='foreignkey')
    op.drop_column('organisation_calendar', 'organisation_branch_id')
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.drop_column('attendance_records', 'branches')
    # ### end Alembic commands ###
