"""add shift, department, and user device tables

Revision ID: 8dd2cbc5208f
Revises: f43edbdc37d5
Create Date: 2026-06-25 23:10:25.323200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd2cbc5208f'
down_revision: Union[str, Sequence[str], None] = 'f43edbdc37d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=22), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deparrments', sa.String(length=25), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('shift_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['shift_time'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userdevice',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('device_unique_id', sa.String(), nullable=False),
    sa.Column('firebaseFCM_token', sa.String(), nullable=False),
    sa.Column('refresh_token_id', sa.UUID(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('logout_time', sa.DateTime(), nullable=False),
    sa.Column('is_login', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attendance_records_id', sa.UUID(), nullable=False),
    sa.Column('oranisation_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('log', sa.String(length=225), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_records_id'], ['attendance_records.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['userdevice.id'], ),
    sa.ForeignKeyConstraint(['oranisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('attendance_records', sa.Column('attendance_date', sa.DateTime(), nullable=False))
    op.add_column('attendance_records', sa.Column('work_mode', sa.Enum('WFH', 'WFO', name='workmode'), nullable=False))
    op.alter_column('attendance_records', 'punchin_time',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('attendance_records', 'punchout_time',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_column('attendance_records', 'attendance_data')
    op.add_column('leave_requests', sa.Column('approved_at', sa.DateTime(), nullable=False))
    op.alter_column('organisation', 'organisation_email',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    op.alter_column('organisation', 'address',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    op.alter_column('organisation', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('organisation', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('organisation', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organisation', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('organisation', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('organisation', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('organisation', 'address',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    op.alter_column('organisation', 'organisation_email',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    op.drop_column('leave_requests', 'approved_at')
    op.add_column('attendance_records', sa.Column('attendance_data', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('attendance_records', 'punchout_time',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('attendance_records', 'punchin_time',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('attendance_records', 'work_mode')
    op.drop_column('attendance_records', 'attendance_date')
    op.drop_table('attendance_log')
    op.drop_table('userdevice')
    op.drop_table('department')
    op.drop_table('shift')
    # ### end Alembic commands ###
