"""new record are add with organisation table relation with subcription 

Revision ID: 8f001274c0fd
Revises: 3939fe218014
Create Date: 2026-06-23 13:52:57.435030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f001274c0fd'
down_revision: Union[str, Sequence[str], None] = '3939fe218014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
