"""punchin and punch out checked add 

Revision ID: 91d1105fc9d7
Revises: 663261609f46
Create Date: 2026-06-27 09:23:50.210654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d1105fc9d7'
down_revision: Union[str, Sequence[str], None] = '663261609f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('is_punchin', sa.Boolean(), nullable=False))
    op.add_column('attendance_records', sa.Column('is_punchout', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_records', 'is_punchout')
    op.drop_column('attendance_records', 'is_punchin')
    # ### end Alembic commands ###
