"""correction

Revision ID: 92c5da345de9
Revises: e1236f401216
Create Date: 2026-07-19 19:00:37.633602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92c5da345de9'
down_revision: Union[str, Sequence[str], None] = 'e1236f401216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')

    op.add_column('employee_role', sa.Column('role_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'employee_role', 'organisation_roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.alter_column('employees', 'join_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index('idx_user_id', 'employees', ['user_id', 'organisation_id'], unique=False)
    op.drop_constraint(op.f('subscriptions_organisation_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'organisation', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.add_column('system_role_permissions', sa.Column('system_roles_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'system_role_permissions', 'system_roles', ['system_roles_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user', 'account_type',
               existing_type=postgresql.ENUM('SYSTEM', 'ORGANISATION', name='accounttype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'account_type',
               existing_type=postgresql.ENUM('SYSTEM', 'ORGANISATION', name='accounttype'),
               nullable=True)
    op.drop_constraint(None, 'system_role_permissions', type_='foreignkey')
    op.drop_column('system_role_permissions', 'system_roles_id')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_organisation_id_fkey'), 'subscriptions', 'organisation', ['organisation_id'], ['id'])
    op.drop_index('idx_user_id', table_name='employees')
    op.alter_column('employees', 'join_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint(None, 'employee_role', type_='foreignkey')
    op.drop_column('employee_role', 'role_id')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('role_permissions_permission_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('role_permissions_role_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('role_permissions_pkey'))
    )
    op.create_table('token',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['userdevice.id'], name=op.f('token_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('token_pkey'))
    )
    op.create_table('role',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organisation.id'], name=op.f('role_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('role_pkey'))
    )
    # ### end Alembic commands ###
