"""new record are add with organisation table relation with subcription 

Revision ID: 9342a7606556
Revises: 0551967971ab
Create Date: 2026-06-23 09:19:41.814394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9342a7606556'
down_revision: Union[str, Sequence[str], None] = '0551967971ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('organisation_subcription_fkey'), 'organisation', type_='foreignkey')
    op.drop_column('organisation', 'subcription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('subcription', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('organisation_subcription_fkey'), 'organisation', 'subscriptions', ['subcription'], ['id'])
    # ### end Alembic commands ###
