"""enum added to the permission table

Revision ID: 9393994c3496
Revises: d9b626cd6aa3
Create Date: 2026-07-02 00:00:27.927697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9393994c3496'
down_revision: Union[str, Sequence[str], None] = 'd9b626cd6aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('scope', postgresql.ENUM('ORGANIZATION', 'SYSTEM_ADMIN', name='permissionscopenum'), nullable=False))
    op.add_column('permissions', sa.Column('assignable', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'assignable')
    op.drop_column('permissions', 'scope')
    # ### end Alembic commands ###
