"""relation name change

Revision ID: 980aa36c9fbc
Revises: 4537285c9ace
Create Date: 2026-07-17 13:38:22.780989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '980aa36c9fbc'
down_revision: Union[str, Sequence[str], None] = '4537285c9ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')

    op.add_column(

        "organisation_roles",

        sa.Column(

            "organisation_id",

            sa.Uuid(),

            nullable=False,

        )

    )

    op.create_foreign_key(

        None,

        "organisation_roles",

        "organisation",

        ["organisation_id"],

        ["id"],

    )
    op.drop_constraint(op.f('organisation_roles_role_name_organization_id_key'), 'organisation_roles', type_='unique')
    op.create_unique_constraint(None, 'organisation_roles', ['role_name', 'organisation_id'])
    op.drop_column('organisation_roles', 'organization_id')
    op.alter_column('user', 'account_type',
               existing_type=postgresql.ENUM('SYSTEM', 'ORGANISATION', name='accounttype'),
               nullable= True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='unique')
    op.alter_column('user', 'account_type',
               existing_type=postgresql.ENUM('SYSTEM', 'ORGANISATION', name='accounttype'),
               nullable=True)
    op.add_column('organisation_roles', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organisation_roles', type_='unique')
    op.create_unique_constraint(op.f('organisation_roles_role_name_organization_id_key'), 'organisation_roles', ['role_name', 'organization_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('organisation_roles', 'organisation_id')
    op.drop_constraint(None, 'employee_role', type_='unique')
    op.create_table('token',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['userdevice.id'], name=op.f('token_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('token_pkey'))
    )
    # ### end Alembic commands ###
