"""relation correction

Revision ID: a33d7d1dcded
Revises: 6df2ac84bd22
Create Date: 2026-08-05 11:41:08.927503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33d7d1dcded'
down_revision: Union[str, Sequence[str], None] = '6df2ac84bd22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_employee_face_id'), table_name='employee_face')
    op.create_index('idx_employee_face_id', 'employee_face', ['employee_id', 'id'], unique=False)
    op.drop_constraint(op.f('employee_face_employee_id_fkey'), 'employee_face', type_='foreignkey')
    op.create_foreign_key(None, 'employee_face', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_face', type_='foreignkey')
    op.create_foreign_key(op.f('employee_face_employee_id_fkey'), 'employee_face', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_employee_face_id', table_name='employee_face')
    op.create_index(op.f('idx_employee_face_id'), 'employee_face', ['employee_id'], unique=True)
    # ### end Alembic commands ###
