"""User table has a status coloum21

Revision ID: c6e7626f8e44
Revises: 50fd205791a4
Create Date: 2026-06-29 12:26:34.332528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e7626f8e44'
down_revision: Union[str, Sequence[str], None] = '50fd205791a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'department',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('employees', 'designation',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'designation',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('employees', 'department',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
