"""Fix permission UUID

Revision ID: cc4d81fe06af
Revises: 0ac9306a5a2c
Create Date: 2026-06-26 12:16:20.210522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc4d81fe06af'
down_revision: Union[str, Sequence[str], None] = '0ac9306a5a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_records', 'attendance_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_unique_constraint('uq_employee_attendance_date', 'attendance_records', ['employee_id', 'attendance_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_attendance_date', 'attendance_records', type_='unique')
    op.alter_column('attendance_records', 'attendance_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
