"""organisation code now unique 

Revision ID: d0f8c672cd32
Revises: f43d43e33a2d
Create Date: 2026-06-23 10:01:01.554166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f8c672cd32'
down_revision: Union[str, Sequence[str], None] = 'f43d43e33a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'organisation', ['organisation_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisation', type_='unique')
    # ### end Alembic commands ###
