"""organisation table now has number of employee

Revision ID: d71b28122078
Revises: e9cdb22ff34d
Create Date: 2026-06-27 13:23:19.882842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71b28122078'
down_revision: Union[str, Sequence[str], None] = 'e9cdb22ff34d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('number_of_employee', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'number_of_employee')
    # ### end Alembic commands ###
