"""device table now can access to token  , and token table has revoke option fro

Revision ID: db4889e7654a
Revises: 9e47bb83410b
Create Date: 2026-07-07 08:52:27.667653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db4889e7654a'
down_revision: Union[str, Sequence[str], None] = '9e47bb83410b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.add_column('userdevice', sa.Column('firebase_fcm_token', sa.String(), nullable=False))
    op.alter_column('userdevice', 'logout_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint(None, 'userdevice', ['device_unique_id'])
    op.drop_column('userdevice', 'firebaseFCM_token')
    op.drop_column('userdevice', 'refresh_token_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdevice', sa.Column('refresh_token_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('userdevice', sa.Column('firebaseFCM_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'userdevice', type_='unique')
    op.alter_column('userdevice', 'logout_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('userdevice', 'firebase_fcm_token')
    op.create_table('token',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['userdevice.id'], name=op.f('token_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('token_pkey'))
    )
    # ### end Alembic commands ###
