"""initial tables

Revision ID: dd86f48cb570
Revises: 
Create Date: 2026-06-22 13:54:52.817979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd86f48cb570'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('attendance_records', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('leave_requests', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('leave_requests', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('organisation', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('organisation', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('organisation', 'updated_at')
    op.drop_column('organisation', 'created_at')
    op.drop_column('leave_requests', 'updated_at')
    op.drop_column('leave_requests', 'created_at')
    op.drop_column('attendance_records', 'updated_at')
    op.drop_column('attendance_records', 'created_at')
    # ### end Alembic commands ###
