"""indel added for profile picture

Revision ID: dd900dbf585e
Revises: 63bae348f012
Create Date: 2026-09-25 18:55:02.400197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd900dbf585e'
down_revision: Union[str, Sequence[str], None] = '63bae348f012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_employee_profile_imageemployee_id', 'employee_details', ['employee_profile_image'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_employee_profile_imageemployee_id', table_name='employee_details')
    # ### end Alembic commands ###
