"""holidays calender table added for organisation holidays

Revision ID: e2bae631c0a9
Revises: 273622b75671
Create Date: 2026-08-31 10:52:36.917005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bae631c0a9'
down_revision: Union[str, Sequence[str], None] = '273622b75671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation_calendar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('finance_year_start', sa.Date(), nullable=False),
    sa.Column('finance_year_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidays_calender',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_calender_id', sa.UUID(), nullable=False),
    sa.Column('holidays_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=225), nullable=False),
    sa.Column('type_of_holiday', sa.Enum('NATIONAL', 'ORGANIZATION', 'OTHER', name='holidaytype'), nullable=False),
    sa.Column('status', sa.Enum('CANCELED', 'SUSPENDED', 'ACTIVE', name='holidaystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_calender_id'], ['organisation_calendar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holidays_calender')
    op.drop_table('organisation_calendar')
    # ### end Alembic commands ###
