"""unique constrain added

Revision ID: e9cdb22ff34d
Revises: 064760d17417
Create Date: 2026-06-27 13:19:16.276509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9cdb22ff34d'
down_revision: Union[str, Sequence[str], None] = '064760d17417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('organisation_id', sa.UUID(), nullable=False))
    op.add_column('employees', sa.Column('employee_code', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('employees_emplopyee_code_key'), 'employees', type_='unique')
    op.create_unique_constraint('uq_org_employee_code', 'employees', ['organisation_id', 'employee_code'])
    op.create_unique_constraint(None, 'employees', ['employee_code'])
    op.drop_constraint(op.f('employees_oganisation_id_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'organisation', ['organisation_id'], ['id'])
    op.drop_column('employees', 'oganisation_id')
    op.drop_column('employees', 'emplopyee_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('emplopyee_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('oganisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_oganisation_id_fkey'), 'employees', 'organisation', ['oganisation_id'], ['id'])
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_constraint('uq_org_employee_code', 'employees', type_='unique')
    op.create_unique_constraint(op.f('employees_emplopyee_code_key'), 'employees', ['emplopyee_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('employees', 'employee_code')
    op.drop_column('employees', 'organisation_id')
    # ### end Alembic commands ###
