"""uniqueContraint create for oranisation_id and department_name

Revision ID: f2208cf5b2ba
Revises: 00c6cf7d58ee
Create Date: 2026-07-02 10:39:39.743568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2208cf5b2ba'
down_revision: Union[str, Sequence[str], None] = '00c6cf7d58ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('name', sa.String(length=25), nullable=False))
    op.add_column('department', sa.Column('organisation_id', sa.UUID(), nullable=False))
    op.create_unique_constraint('uq_department_org_name', 'department', ['organisation_id', 'name'])
    op.drop_constraint(op.f('department_organization_id_fkey'), 'department', type_='foreignkey')
    op.create_foreign_key(None, 'department', 'organisation', ['organisation_id'], ['id'])
    op.drop_column('department', 'organization_id')
    op.drop_column('department', 'deparrments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('deparrments', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.add_column('department', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.create_foreign_key(op.f('department_organization_id_fkey'), 'department', 'organisation', ['organization_id'], ['id'])
    op.drop_constraint('uq_department_org_name', 'department', type_='unique')
    op.drop_column('department', 'organisation_id')
    op.drop_column('department', 'name')
    # ### end Alembic commands ###
