"""organisation now identifed with unique code

Revision ID: f43d43e33a2d
Revises: 9342a7606556
Create Date: 2026-06-23 09:59:10.092839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43d43e33a2d'
down_revision: Union[str, Sequence[str], None] = '9342a7606556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('organisation_code', sa.String(length=225), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'organisation_code')
    # ### end Alembic commands ###
