"""new deatils are added 

Revision ID: f43edbdc37d5
Revises: f50cd9e79a40
Create Date: 2026-06-24 12:10:41.447213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43edbdc37d5'
down_revision: Union[str, Sequence[str], None] = 'f50cd9e79a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('address', sa.String(length=225), nullable=True))
    op.add_column('organisation', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('organisation', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('organisation', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('organisation', sa.Column('allowed_radius', sa.Integer(), nullable=True))
    op.alter_column('organisation', 'organisation_email',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organisation', 'organisation_email',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    op.drop_column('organisation', 'allowed_radius')
    op.drop_column('organisation', 'longitude')
    op.drop_column('organisation', 'latitude')
    op.drop_column('organisation', 'phone_number')
    op.drop_column('organisation', 'address')
    # ### end Alembic commands ###
