"""indexes add and organisation email are added 

Revision ID: f50cd9e79a40
Revises: 8f001274c0fd
Create Date: 2026-06-24 10:06:53.748135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50cd9e79a40'
down_revision: Union[str, Sequence[str], None] = '8f001274c0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('organisation_email', sa.String(length=225), nullable=True))
    op.drop_constraint(op.f('organisation_organisation_code_key'), 'organisation', type_='unique')
    op.create_index(op.f('ix_organisation_organisation_code'), 'organisation', ['organisation_code'], unique=True)
    op.create_index(op.f('ix_organisation_organisation_email'), 'organisation', ['organisation_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organisation_organisation_email'), table_name='organisation')
    op.drop_index(op.f('ix_organisation_organisation_code'), table_name='organisation')
    op.create_unique_constraint(op.f('organisation_organisation_code_key'), 'organisation', ['organisation_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('organisation', 'organisation_email')
    # ### end Alembic commands ###
