"""Sift and department are maped with banch table now

Revision ID: f81547533b6f
Revises: 8ad0782beb32
Create Date: 2026-09-26 09:46:23.982738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81547533b6f'
down_revision: Union[str, Sequence[str], None] = '8ad0782beb32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'department', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'branch_id')
    # ### end Alembic commands ###
